/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package backend;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import backend.RefreshListener; // Tambahkan ini di bagian import
import javax.swing.text.AbstractDocument;

/**
 *
 * @author HP
 */
public class PanelPemasok extends javax.swing.JFrame {

    private boolean isEditMode = false;
    private String idPemasok = null;

    /**
     * Creates new form PanelPemasok
     */
    public PanelPemasok() {
        initComponents();
        String nama_pemasok = null;
        String no_telp = null;
        String alamat = null;

        txt_nama.setText(nama_pemasok);
        txt_notelp.setText(no_telp);
        txt_alamat.setText(alamat);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        
        ((AbstractDocument) txt_notelp.getDocument()).setDocumentFilter(new filter());
    }

    
    public PanelPemasok(String id, String nama, String telp, String alamat) {
        initComponents();
        txt_nama.setText(nama);
        txt_notelp.setText(telp);
        txt_alamat.setText(alamat);
        this.idPemasok = id;
        isEditMode = true;
        
        ((AbstractDocument) txt_notelp.getDocument()).setDocumentFilter(new filter());
    }

    private String generateNewId(Connection conn, String prefix) throws SQLException {
        String sql = "SELECT id_pemasok FROM pemasok ORDER BY id_pemasok DESC LIMIT 1";
        PreparedStatement pst = conn.prepareStatement(sql);
        java.sql.ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            String lastId = rs.getString("id_pemasok");
            // Pastikan format ID sesuai dengan prefix yang diminta
            if (lastId.startsWith(prefix)) {
                int lastNum = Integer.parseInt(lastId.substring(prefix.length()));
                int newNum = lastNum + 1;
                return prefix + String.format("%03d", newNum); // format 3 digit: PS001
            }
        }
        // Jika belum ada data atau format tidak sesuai
        return prefix + "001";
    }

    private RefreshListener refreshListener;

    public void setRefreshListener(RefreshListener listener) {
        this.refreshListener = listener;
    }
    
    public interface RefreshListener {
    void onDataUpdated();
}

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_simpan = new javax.swing.JButton();
        txt_alamat = new javax.swing.JTextField();
        txt_notelp = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_simpan.setContentAreaFilled(false);

        btn_simpan.setBorderPainted(false);
        btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/penyewaan/Button Simpan.png"))); // NOI18N
        btn_simpan.setContentAreaFilled(false);
        btn_simpan.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/penyewaan/Button Simpan Select.png"))); // NOI18N
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 110, 40));

        txt_nama.setText("Masukkan Nama Lengkap"); txt_nama.setForeground(Color.GRAY);
        txt_alamat.setBackground(new java.awt.Color(255, 244, 232));
        txt_alamat.setBorder(null);
        txt_alamat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_alamatFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_alamatFocusLost(evt);
            }
        });
        txt_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alamatActionPerformed(evt);
            }
        });
        jPanel1.add(txt_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 440, 30));

        txt_nama.setText("Masukkan Nama Lengkap"); txt_nama.setForeground(Color.GRAY);
        txt_notelp.setBackground(new java.awt.Color(255, 244, 232));
        txt_notelp.setBorder(null);
        txt_notelp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_notelpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_notelpFocusLost(evt);
            }
        });
        txt_notelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_notelpActionPerformed(evt);
            }
        });
        jPanel1.add(txt_notelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 440, 30));

        txt_nama.setText("Masukkan Nama Lengkap"); txt_nama.setForeground(Color.GRAY);
        txt_nama.setBackground(new java.awt.Color(255, 244, 232));
        txt_nama.setBorder(null);
        txt_nama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_namaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_namaFocusLost(evt);
            }
        });
        jPanel1.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 440, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/panelpemasok/Data Pemasok.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/panelpemasok/Input-an Pemasok.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel1.setBackground(new java.awt.Color(206, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/panelpemasok/bg.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_namaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_namaFocusGained
        if (txt_nama.getText().equals("Masukkan Nama Lengkap")) {
            txt_nama.setText("");
            txt_nama.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_namaFocusGained

    private void txt_namaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_namaFocusLost
        if (txt_nama.getText().isEmpty()) {
            txt_nama.setText("Masukkan Nama Lengkap");
            txt_nama.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txt_namaFocusLost

    private void txt_notelpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_notelpFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_notelpFocusGained

    private void txt_notelpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_notelpFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_notelpFocusLost

    private void txt_notelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_notelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_notelpActionPerformed

    private void txt_alamatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_alamatFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatFocusGained

    private void txt_alamatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_alamatFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatFocusLost

    private void txt_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
                                       
    String nama = txt_nama.getText();
    String telp = txt_notelp.getText();
    String alamat = txt_alamat.getText();

    try {
        backend.Koneksi.config(); // PENTING: panggil ini dulu
        Connection conn = backend.Koneksi.getConnection(); // baru ambil koneksi

        if (isEditMode) {
            // Mode edit: lakukan UPDATE
            String sql = "UPDATE pemasok SET nama_pemasok=?, no_telp=?, alamat=? WHERE id_pemasok=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, nama);
            pst.setString(2, telp);
            pst.setString(3, alamat);
            pst.setString(4, idPemasok);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
        } else {
            // Mode tambah baru: lakukan INSERT
            String newId = generateNewId(conn, "PS");
            String sql = "INSERT INTO pemasok (id_pemasok, nama_pemasok, no_telp, alamat) VALUES (?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, newId);
            pst.setString(2, nama);
            pst.setString(3, telp);
            pst.setString(4, alamat);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
        }

        // Panggil listener untuk refresh data
        if (refreshListener != null) {
            refreshListener.onDataUpdated();
        }
        
        dispose(); // Tutup form setelah simpan
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage());
    }
                                       
    

    }//GEN-LAST:event_btn_simpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelPemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelPemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelPemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelPemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelPemasok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nama1;
    private javax.swing.JTextField txt_nama2;
    private javax.swing.JTextField txt_notelp;
    // End of variables declaration//GEN-END:variables
}
